# Generated by Django 3.0.6 on 2020-05-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=13)),
                ('numero_tarjeta_de_credito', models.CharField(max_length=13)),
                ('limite_de_credito', models.IntegerField()),
                ('tipo_de_persona_choice', models.CharField(choices=[('Jur', 'Juridica'), ('Fis', 'Fisica')], max_length=3)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=13)),
                ('tanda_labor_choices', models.CharField(choices=[('Mat', 'Matutina'), ('Noc', 'Nocturna'), ('Ves', 'Vespertina')], max_length=3)),
                ('porciento_comision', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipodeCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipodeVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('numero_de_chasis', models.IntegerField()),
                ('numero_de_motor', models.IntegerField()),
                ('numero_de_placa', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Modelo')),
                ('tipodecombustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.TipodeCombustible')),
                ('tipodevehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.TipodeVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RentayDevolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_renta', models.IntegerField(max_length=10)),
                ('fecha_renta', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('cliente_rentayd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Cliente')),
                ('empleado_rentayd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Empleado')),
                ('vehiculo_rentayd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_combustible_choices', models.CharField(choices=[('25%', '1/4'), ('50%', '1/2'), ('75%', '3/4'), ('100%', 'Full')], max_length=4)),
                ('ralladuras', models.BooleanField(default=False)),
                ('goma_de_repuesto', models.BooleanField(default=False)),
                ('gato', models.BooleanField(default=False)),
                ('roturas_cristal', models.BooleanField(default=False)),
                ('estado_gomas', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('empleado_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Empleado')),
                ('identificador_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaCar.Vehiculo')),
            ],
        ),
    ]
