# Generated by Django 3.0.6 on 2020-05-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0003_auto_20200524_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='cantidad_combustible_choices',
            new_name='cantidad_combustible',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tipodecombustible',
            new_name='tipo_de_combustible',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tipodevehiculo',
            new_name='tipo_de_vehiculo',
        ),
    ]
