# Generated by Django 3.0.6 on 2020-05-25 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0004_auto_20200524_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentaydevolucion',
            name='fecha_devolucion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentaydevolucion',
            name='fecha_renta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
