# Generated by Django 3.0.6 on 2020-05-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0005_auto_20200524_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaydevolucion',
            name='cantidad_de_dias',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentaydevolucion',
            name='comentario',
            field=models.CharField(default=1355, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentaydevolucion',
            name='monto_por_dia',
            field=models.FloatField(default=142414),
            preserve_default=False,
        ),
    ]
