# Generated by Django 3.0.6 on 2020-05-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0006_auto_20200524_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='rentaydevolucion',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
