# Generated by Django 3.0.6 on 2020-06-09 03:13

from django.db import migrations, models
import rentaCar.validations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0008_auto_20200608_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[rentaCar.validations.validar_digito_verificador]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[rentaCar.validations.validar_digito_verificador]),
        ),
    ]
