# Generated by Django 3.0.6 on 2020-06-09 03:43

import django.core.validators
from django.db import migrations, models
import rentaCar.validations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0009_auto_20200608_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[rentaCar.validations.validar_digito_verificador, django.core.validators.RegexValidator(regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[rentaCar.validations.validar_digito_verificador, django.core.validators.RegexValidator(regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
    ]
