# Generated by Django 3.0.6 on 2020-06-10 23:03

from django.db import migrations, models
import rentaCar.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0012_auto_20200610_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaydevolucion',
            name='Numero_renta',
        ),
        migrations.AddField(
            model_name='rentaydevolucion',
            name='numero_renta',
            field=models.CharField(default=rentaCar.models.generar_numero_renta, max_length=50),
        ),
    ]
