# Generated by Django 3.0.6 on 2020-06-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaCar', '0013_auto_20200610_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
